include: package:flutter_lints/flutter.yaml
linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  exclude:
    - app/**/*.g.dart
    - app/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - app/**/*.gr.dart
    - lib/**/*.gr.dart
    - test/**
