name: eidupay
description: A new Flutter project.

version: 2.0.4+49

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  camera: ^0.9.2
  carousel_slider: ^4.0.0
  device_info: ^2.0.2
  dropdown_search: ^1.0.3
  easy_mask: ^2.0.1
  encrypt: ^5.0.1
  expandable: ^5.0.1
  ffi: ^1.1.2
  firebase_analytics: ^9.0.5
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.6
  fl_chart: ^0.40.0
  fluttercontactpicker: ^4.5.1
  flutter_html: ^2.1.5
  flutter_image_compress: ^1.1.0
  flutter_launcher_icons: ^0.9.2
  flutter_local_notifications: ^9.3.2
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  fluttertoast: ^8.0.9
  flutter_verification_code: ^1.0.4
  get: ^4.3.8
  get_it: ^7.2.0
  google_api_availability: ^3.0.1
  google_fonts: ^2.1.0
  http: ^0.13.3
  http_parser: ^4.0.0
  image: ^3.0.8
  image_picker: ^0.8.4+1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  local_auth: ^1.1.6
  lottie: ^1.2.0
  otp_autofill: ^2.1.0
  package_info: ^2.0.2
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  qr_code_scanner: ^0.5.2
  share: ^2.0.4
  shared_preferences: ^2.0.7
  showcaseview: ^1.1.4
  shimmer: ^2.0.0
  screenshot: ^1.2.3
  path_provider: ^2.0.0
  url_launcher: ^6.0.10
  image_cropper: ^1.5.1
  launch_review: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  flutter_lints: ^1.0.4
  json_serializable: ^4.1.3
  change_app_package_name: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - assets/lottie/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"